default_url_options: 
  host: 3008.brandymint.ru
  protocol: https

bot_link: https://telegram.me/LARA_HELPER_BOT
# https://t.me/lara_helper_bot

welcome_message: |-
  Я - Лара - электронный дежурный.
  Ученикам я рассылаю домашнее задание и выдаю ⭐️ за успехи.
  Учителям и родителям я помогаю наблюдать за успехами учеников.

  Я могу выполнять команды. 
  Напиши /help и я покажу список команд.

help_message: |-
  /wallet - Посмотреть сколько ⭐️ у тебя накопилось (для ученика)
  /class - Посмотреть сколько ⭐️ у всего класса
  /give - Выдать ⭐️ ученику (для учителя)

admin_message: |-
  /admin - Это сообщение
  /invite - Пригласить участника (ученика, родителя или учителя)
  /login - Авторизация в web

